services:
  postgres:
    image: postgres:16-alpine
    container_name: smetrics-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7
    container_name: smetrics-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: smetrics-config-server
    ports:
      - "8888:8888"

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    container_name: smetrics-discovery-server
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: smetrics-api-gateway
    depends_on:
      - config-server
      - discovery-server
    environment:
      CONFIG_SERVER_URI: http://config-server:8888
      EUREKA_URI: http://discovery-server:8761/eureka
    ports:
      - "8080:8080"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: smetrics-user-service
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      CONFIG_SERVER_URI: http://config-server:8888
      EUREKA_URI: http://discovery-server:8761/eureka
      DB_URL: jdbc:postgresql://postgres:5432/userdb
      DB_USER: postgres
      DB_PASSWORD: root
    ports:
      - "8081:8081"

  stats-service:
    build:
      context: .
      dockerfile: stats-service/Dockerfile
    container_name: smetrics-stats-service
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
      mongo:
        condition: service_healthy
      user-service:
        condition: service_started
    environment:
      CONFIG_SERVER_URI: http://config-server:8888
      EUREKA_URI: http://discovery-server:8761/eureka
      MONGO_URI: mongodb://mongo:27017/statsdb
    ports:
      - "8082:8082"

volumes:
  postgres_data:
  mongo_data:
