server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/api/stats/**
